### ISSUE TITLE
skybox altitude limit feature request

### ISSUE THREAD

**Issue by scr267** [t-affeldt/climate_api#10]
I'm running the regional_weather modpack and it doesn't allow Shara's other_worlds mod to change the skybox in space.  

I was wondering if you could add a setting to limit the altitude at which the climate_api skybox is effective.

I did read the documentation explaining that it may not work well with other skybox modifying mods, but it would be a nice feature if it "let go" of its effect past a certain altitude.

Thank you for your consideration!

**Comment by t-affeldt** [comment]
Hello!
Sorry for the very late reply as I don't have any time for modding at the moment.
This feature is already available. By default, it is set to not apply any weather effects above the clouds, i.e. an altitude of 120 nodes.
You can customize this value in the settings for Regional Weather. Look for a setting labeled "Maximum height of weather effects" (called _regional_weather_max_height_ in the settingstypes).
